<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Scenario: Delete an Recipe out of range 3 catch an exception" tests="2" skipped="0" failures="0" errors="0" timestamp="2022-02-12T06:52:18" hostname="DESKTOP-5B35QQB" time="0.0">
  <properties/>
  <testcase name="When user delete Recipe xy it will catch an exception" classname="Scenario: Delete an Recipe out of range 3 catch an exception" time="0.0"/>
  <testcase name="classMethod" classname="Scenario: Delete an Recipe out of range 3 catch an exception" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
